modal-ingridiants
Yuliia21BM/team-project-ice-cream-shop pull request #24
Opened 2022-09-17 13:43 UTC by MariaDekhtiaruk

First commit.

2022-09-17 16:47 UTC, Yuliia21BM requested changes
Зміни все що я написала в html. І можеш в цій ж гілці доробити scss

2022-09-17 16:47 UTC, Yuliia21BM commented on src/partials/modal-ingridients.html
> +mariaaaaa
З картинками щось дійсно не так. Вони мають бути ідеально круглі.

2022-09-17 16:47 UTC, Yuliia21BM commented on src/partials/modal-ingridients.html
> +    <h2 class="modal-ingrid-title">Chocolate icecream </h2>
Тут h3

2022-09-17 16:47 UTC, Yuliia21BM commented on src/partials/modal-ingridients.html
> +    <h2 class="visually-hidden">callories</h2>
Тут можна не давати заголовку. Або тоді h4

2022-09-17 16:47 UTC, Yuliia21BM commented on src/partials/modal-ingridients.html
> +        <h3 class="Ingredients-title">Ingredients</h3>
Тут теж не обов'язкоао тайтл. Або h4

2022-09-17 16:47 UTC, Yuliia21BM commented on src/partials/modal-ingridients.html
> +                <p class="ingredients-list-text">100ml</p>
Де цифри краще зробити span

2022-09-17 16:47 UTC, Yuliia21BM commented on src/partials/modal-ingridients.html
> +        <button type="submit" class="ingredients-input-button ">Submit</button>
В батон треба дати спочатку утилітний клас який я створила а тоді у своєму корегувати

2022-09-18 15:13 UTC, MariaDekhtiaruk commented on src/partials/modal-ingridients.html
> +mariaaaaa
done

2022-09-18 15:13 UTC, MariaDekhtiaruk commented on src/partials/modal-ingridients.html
> +    <h2 class="modal-ingrid-title">Chocolate icecream </h2>
done

2022-09-18 15:14 UTC, MariaDekhtiaruk commented on src/partials/modal-ingridients.html
> +    <h2 class="visually-hidden">callories</h2>
done

2022-09-18 15:14 UTC, MariaDekhtiaruk commented on src/partials/modal-ingridients.html
> +        <h3 class="Ingredients-title">Ingredients</h3>
done

2022-09-18 15:14 UTC, MariaDekhtiaruk commented on src/partials/modal-ingridients.html
> +        <button type="submit" class="ingredients-input-button ">Submit</button>
done

2022-09-18 15:14 UTC, MariaDekhtiaruk commented on src/partials/modal-ingridients.html
> +                <p class="ingredients-list-text">100ml</p>
left p

2022-09-18 19:33 UTC, Yuliia21BM approved these changes

2022-09-18 19:34 UTC, merged